apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-injector-test
  name: vault-injector-test
  namespace: vault-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vault-injector-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-test: secret/data/test
        vault.hashicorp.com/agent-inject-status: update
        vault.hashicorp.com/role: internal-app
      labels:
        app: vault-injector-test
    spec:
      serviceAccountName: vault-secret-read
      containers:
      - image: alpine
        command:
          - "sh"
          - "-c"
          - "cat /vault/secrets/test && sleep 10000"
        imagePullPolicy: Always
        name: vault-injector-test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30