# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-backend  
spec:
  selector:  # backend application pod labels should match these
    app: to-do-app
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-backend
  labels: 
    app: to-do-app
    tier: backend
spec:
  replicas: 2    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: to-do-app
      tier: backend
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-test: secret/data/test
        vault.hashicorp.com/role: internal-app
        vault.hashicorp.com/agent-inject-template-DB_HOST: |
          {{- with secret "secret/data/test" -}}
          export DB_HOST={{ .Data.data.host }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-DB_NAME: |
          {{- with secret "secret/data/test" -}}
          export DB_NAME={{ .Data.data.name }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-DB_USERNAME: |
          {{- with secret "secret/data/test" -}}
          export DB_USERNAME={{ .Data.data.username }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-DB_PASSWORD: |
          {{- with secret "secret/data/test" -}}
          export DB_PASSWORD={{ .Data.data.password }}
          {{- end }}
      labels: # Must match 'Service' and 'Deployment' labels
        app: to-do-app
        tier: backend  
    spec:                 
      serviceAccountName: vault-secret-read
      containers: 
      - name: to-do-app-backend 
        image: kubernetesdemo/to-do-app-backend   # docker image of backend application
        env:
          - name: DB_HOST
            value: "vault:secrets/data/test#host"
          - name: DB_NAME
            value: "vault:secrets/data/test#name"
          - name: DB_USERNAME
            value: "vault:secrets/data/test#username"
          - name: DB_PASSWORD
            value: "vault:secrets/data/test#password"
        ports:
        - containerPort: 8080
