# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-backend  
spec:
  selector:  # backend application pod labels should match these
    app: to-do-app
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-backend
  labels: 
    app: to-do-app
    tier: backend
spec:
  replicas: 2    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: to-do-app
      tier: backend
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault-spring
        vault.hashicorp.com/agent-inject-secret-config.json: test
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{- with secret "test/data/test" -}}
          {"DB_NAME":"{{ .Data.data.name }}","DB_PASSWORD":"{{ .Data.data.password }}", "DB_USERNAME":"{{ .Data.data.username }}", "DB_HOST":"{{ .Data.data.host }}"}
          {{- end }}
        vault.hashicorp.com/secret-volume-path-config.json: /test
      labels: # Must match 'Service' and 'Deployment' labels
        app: to-do-app
        tier: backend
    spec:                 
      containers: 
      - name: to-do-app-backend 
        image: kubernetesdemo/to-do-app-backend   # docker image of backend application
        ports:
        - containerPort: 8080
        
  
      labels:
        app: vault-test
    spec:
      containers:
      - image: nginx
        name: vault-test
